### ISSUE TITLE
Unable to run test_labjack.py after successful installation

### ISSUE THREAD

**Issue by SparshJ** [john-veillette/labjack-to-lsl#2]
Hey,

I'm having trouble running the test scripts after installation. Error is 'labjack not found'. Included error lines below. I used
conda env create -f environment.yml using your supplied yml file. Could you please help me? 

(labjack) C:\Users\spars\xyz\Labjack LSL>python test-labjack2.py
Traceback (most recent call last):
  File "test-labjack2.py", line 7, in <module>
    ljs = LabJackStream(n_channels = 1, sfreq = 50, device_class = U3)
  File "C:\Users\spars\xyz\Labjack LSL\util\labjack\stream.py", line 21, in __init__
    self._init_labjack(device_class)
  File "C:\Users\spars\xyz\util\labjack\stream.py", line 30, in _init_labjack
    d = device_class()
  File "C:\Users\spars\anaconda3\envs\labjack\lib\site-packages\u3.py", line 102, in __init__
    self.open(**kargs)
  File "C:\Users\spars\anaconda3\envs\labjack\lib\site-packages\u3.py", line 137, in open
    Device.open(self, 3, firstFound = firstFound, serial = serial, localId = localId, devNumber = devNumber, handleOnly = handleOnly, LJSocket = LJSocket )
  File "C:\Users\spars\anaconda3\envs\labjack\lib\site-packages\LabJackPython.py", line 627, in open
    d = openLabJack(devType, ct, firstFound = True, handleOnly = handleOnly, LJSocket = LJSocket)
  File "C:\Users\spars\anaconda3\envs\labjack\lib\site-packages\LabJackPython.py", line 1409, in openLabJack
    handle = _openLabJackUsingUDDriver(deviceType, connectionType, firstFound, pAddress, devNumber)
  File "C:\Users\spars\anaconda3\envs\labjack\lib\site-packages\LabJackPython.py", line 1252, in _openLabJackUsingUDDriver
    raise LabJackException(ec)
LabJackPython.LabJackException: LabJack not found

**Comment by john-veillette** [comment]
Are you able to run the examples from the [LabJackPython](https://github.com/labjack/LabJackPython) repository? The error seems to be originating from the U3 package, which is hosted there. (This is assuming you're able to interface with your labjack hardware from other software, just not in Python.)

If you are able to run those examples, it's entirely possible I accidentally coded in something U6-specific in this repository. I only have U6 hardware, so I've never tested the code with a U3. But if you can give me enough details (e.g full code you ran), I'll try to fix it.

Whatever ends up being the problem, please let me know on this issue so other users can see what the solution was!

**Comment by SparshJ** [comment]
I do not see the example python files from that repo anywhere on my PC (including inside my environment). I'm guessing they didn't get automatically downloaded when I built your package using your yml file. I will manually place them in the site-packages directory and try running them now, unless I should install labjackpython manually following their instructions?

**Comment by john-veillette** [comment]
If you can run the line `from u3 import U3` without throwing an error (which it sounds like you can), then the necessary package is already installed in your environment. (It was supposed to, and evidently did, install when you created your conda environment from the yml file.) 

You just need to download and run one of the example files from the LabJackPython repository, no need to install anything else.

**Comment by john-veillette** [comment]
Try downloading and running [this file](https://github.com/labjack/LabJackPython/blob/master/Examples/streamTest.py), uncommenting the appropriate lines to use the U3.

**Comment by SparshJ** [comment]
Hey,

I didn't see your reply soon enough, and ended up installing LabjackPython manually inside my labjack-to-lsl master folder.

I am able to run PWM-loop, streamTest, u3Noise etc. successfully after uncommenting the u3-relevant lines. Now when I try to run test-labjack.py, I get the following error:

 File "test-labjack2.py", line 7, in <module>
    ljs = LabJackStream(n_channels = 1, sfreq = 50, device_class = U3)
  File "C:\Users\spars\xyz\Labjack LSL\util\labjack\stream.py", line 21, in __init__
    self._init_labjack(device_class)
  File "C:\Users\spars\xyz\Labjack LSL\util\labjack\stream.py", line 37, in _init_labjack
    ResolutionIndex = self._res
TypeError: streamConfig() got an unexpected keyword argument 'ChannelNumbers'

**Comment by john-veillette** [comment]
Thanks for checking that. It looks like my code does indeed use U6-specific arguments when initializing the LabJack device. I didn't realize that `U6`, `U3`, and `UE9` had different interfaces. That's good to know, so I appreciate you pointing it out. 

I think the best/most general solution, in the long term, would be for me to update the `LabJackStream` class so that users initialize the appropriate `U...` object for their device outside the class, just as in Lines 28-82 in the [LabJackPython example](https://github.com/labjack/LabJackPython/blob/d4bfa0683b4b5acd2d5851761eadfab80f28bf88/Examples/streamTest.py#L28). So in the future, you would initialize `LabJackStream` like
```
# initialize your device with the appropriate labjack API
d = u3.U3()
d.configU3()
d.getCalibrationData()
d.configIO(FIOAnalog = 3)
d.streamConfig(
    NumChannels = 2, # or whatever values you want for your stream
    PChannels = [0, 1], 
    NChannels = [31, 31], 
    Resolution = 3, 
    ScanFrequency = SCAN_FREQUENCY
)

# then input the initialized device to LabJackStream
ljs = LabJackStream(d)
```
That way, I don't have to consider every possible configuration option users could want.

I don't know quite when I'll be able to get to that though (I'm particularly busy for the next couple of weeks at least), so you could probably use a more near-term solution. You can try modifying the [LabJackStream._init_labjack()](https://github.com/john-veillette/labjack-to-lsl/blob/ae2643ca0defba9d7c8a4bc04c1de0d69a6e8430/util/labjack/stream.py#L29). You could change the parameters directly to what you want, for example:
```
def _init_labjack(self, device_class):
    import u3
    d = u3.U3()
    d.configU3()
    d.getCalibrationData()
    d.configIO(FIOAnalog = 3)
    d.streamConfig(
        NumChannels = 2, # or whatever values you want for your stream
        PChannels = [0, 1], 
        NChannels = [31, 31], 
        Resolution = 3, 
        ScanFrequency = SCAN_FREQUENCY
    )
    self.device = d
```
Just a temporary fix (and might require some additional troubleshooting), but should hopefully get your hardware working for now.

**Comment by SparshJ** [comment]
Thanks a lot ! It worked using the following for my case:

Edits in stream.py:
```
 def _init_labjack(self, device_class):
        import u3
        d = u3.U3()
        d.configU3()
        d.getCalibrationData()
        d.streamConfig(
            NumChannels = 1,
            PChannels = [0], 
            NChannels = [31],
            ScanFrequency = 50,
        )
        self.device = d
```
And then in test-labjack.py I had already added:
```
from util.labjack import LabJackStream
from u3 import U3
import threading
from time import sleep

# start streaming data from labjack on a seperate thread
ljs = LabJackStream(n_channels = 1, sfreq = 50, device_class = U3)
```
I did not change `__init__(self.......)` in stream.py but I'm guessing changing the class to U3 will let me run your original test-labjack.py without the modifications.

i have three follow-up questions:
1.  Does the Resolution=3 in your suggested edit specify 3 decimal places in the streamed voltage? 
2. Looking at the xdf generated from Labrecorder, I see an 'error' in the timestamps of almost 191.7 ms in the 6100th sample (@50Hz), i.e., the difference between the final timestamp and the first timestamp is 122.1917s instead of 122. Is this caused by  labjack-to-lsl or LSL itself? Can I fix it?
3. The first timestamp is 2292.326 which I understand will not give me the absolute time of start of recording. Can I somehow obtain the absolute timestamp (i.e. 2:54:53.560 pm) at which the first sample occurred? 

Thank you very much, again!!

**Comment by john-veillette** [comment]
Glad that worked for you! I'll keep this issue open until I have time to modify `LabJackStream` so this will be easier in the future. 

Re: your questions

1. Resolution=n controls the resolution in bits (i.e. binary) with which your measurement is digitized, not decimal voltage. The "accuracy" or "effective resolution," which is the "decimal places out in units of voltage" quantity to which you refer, is a function of both (a) the resolution index, which is the Resolution=3 parameter here, and (b) the gain parameter, which essentially changes the signal-to-noise ratio going into the analog-to-digital conversion. You can find a more thorough explanation in the labjack documentation [here](https://support.labjack.com/docs/resolution-and-accuracy-app-note). I'm not sure about the U3, but the labjack folks publish a nice table for the U6 [here](https://support.labjack.com/docs/appendix-b-noise-and-resolution-tables-u6-datashee) with approximate accuracy equivalences for different resolution/gain values. (As a side note, lowering the resolution and/or the gain allows your labjack to sample faster, so higher voltage resolution isn't always better, as it trades off with temporal resolution. I just chose Resolution=3 because that's what the LabJackPython example uses.) 
2. The timestamps of any labstreaminglayer (LSL) stream are going to be affected by (a) jitter/variance/noise in the sample timestamps and (b) clock drift, which will matter primarily when you want to sync recording from two different devices/software. LSL doesn't try to correct these inaccuracies at the time of data acquisition to free up your CPU for other things (like if you wanted to process data in real time), but rather it saves the necessary information to correct for jitter and clock drift post-hoc. The official XDF loaders, pyxdf or XDF-Matlab, will handle this correction for you, but if you just look inside the raw XDF file, you'll see the inaccuracies. You can find more details in the [LSL docs](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://labstreaminglayer.readthedocs.io/info/time_synchronization.html&ved=2ahUKEwjXhtPcy9eIAxXKk4kEHRtiHDQQFnoECBwQAQ&usg=AOvVaw0eWfBs_eF0Q9Fxh52uE4mt). If you are still having major timing problems when using an official XDF loader, then I'd try lowering the resolution and/or gain of your labjack device and see if that improves things.
3. You can always record the absolute timestamp at the start of the recording separately, and use that to adjust timestamps later. But if the reason you want to do this is to synchronize your labjack recording with some other recording (or e.g. event times), I suggest recording that other thing into the same XDF file over LSL as well. That will allow you to account for clock drift, which is what LSL is for! (I'd also double check that whatever timestamp you save is, in fact, absolute time. Many Python clocks e.g. in the built-in `time` package may give something like the time since the Python process started, the last time the CPU was restarted, etc.)

**Comment by SparshJ** [comment]
Thanks a lot. Could I possibly email/ping you? I have a couple of small questions and they're no longer related to this package!

**Comment by john-veillette** [comment]
Sure, just accepted your LinkedIn request or you can shoot me an email (jpveillet@gmail)
